export enum GraphFeatures {
  NodeDraggable = "NodeDraggable",
  NodeResizable = "NodeResizable",
  ClickNodeToSelect = "ClickNodeToSelect",
  PanCanvas = "PanCanvas",
  MultipleSelect = "MultipleSelect",
  LassoSelect = "LassoSelect",
  Delete = "Delete",
  AddNewNodes = "AddNewNodes",
  AddNewEdges = "AddNewEdges",
  AddNewPorts = "AddNewPorts",
  AutoFit = "AutoFit",
  CanvasHorizontalScrollable = "CanvasHorizontalScrollable",
  CanvasVerticalScrollable = "CanvasVerticalScrollable",
  NodeHoverView = "NodeHoverView",
  PortHoverView = "PortHoverView",
  AddEdgesByKeyboard = "AddEdgesByKeyboard",
  A11yFeatures = "A11yFeatures",
  EditNode = "EditNode",
  AutoAlign = "AutoAlign",
  UndoStack = "UndoStack",
  CtrlKeyZoom = "CtrlKeyZoom",
  LimitBoundary = "LimitBoundary",
  EditEdge = "EditEdge",
}

export const allFeatures = new Set([
  GraphFeatures.NodeDraggable,
  GraphFeatures.NodeResizable,
  GraphFeatures.ClickNodeToSelect,
  GraphFeatures.PanCanvas,
  GraphFeatures.MultipleSelect,
  GraphFeatures.LassoSelect,
  GraphFeatures.Delete,
  GraphFeatures.AddNewNodes,
  GraphFeatures.AddNewEdges,
  GraphFeatures.AddNewPorts,
  GraphFeatures.CanvasHorizontalScrollable,
  GraphFeatures.CanvasVerticalScrollable,
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.AddEdgesByKeyboard,
  GraphFeatures.A11yFeatures,
  GraphFeatures.AutoFit,
  GraphFeatures.EditNode,
  GraphFeatures.AutoAlign,
  GraphFeatures.UndoStack,
  GraphFeatures.CtrlKeyZoom,
  GraphFeatures.LimitBoundary,
  GraphFeatures.EditEdge,
]);

export const defaultFeatures = new Set([
  GraphFeatures.NodeDraggable,
  GraphFeatures.NodeResizable,
  GraphFeatures.ClickNodeToSelect,
  GraphFeatures.PanCanvas,
  GraphFeatures.MultipleSelect,
  GraphFeatures.Delete,
  GraphFeatures.AddNewNodes,
  GraphFeatures.AddNewEdges,
  GraphFeatures.AddNewPorts,
  GraphFeatures.CanvasHorizontalScrollable,
  GraphFeatures.CanvasVerticalScrollable,
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.AddEdgesByKeyboard,
  GraphFeatures.A11yFeatures,
  GraphFeatures.EditNode,
  GraphFeatures.AutoAlign,
  GraphFeatures.UndoStack,
  GraphFeatures.CtrlKeyZoom,
  GraphFeatures.LimitBoundary,
]);

export const dataReadonlyMode = new Set([
  GraphFeatures.NodeDraggable,
  GraphFeatures.NodeResizable,
  GraphFeatures.ClickNodeToSelect,
  GraphFeatures.PanCanvas,
  GraphFeatures.MultipleSelect,
  GraphFeatures.CanvasHorizontalScrollable,
  GraphFeatures.CanvasVerticalScrollable,
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.A11yFeatures,
  GraphFeatures.CtrlKeyZoom,
  GraphFeatures.LimitBoundary,
]);

export const GanttChartFeatures = new Set([
  GraphFeatures.ClickNodeToSelect,
  GraphFeatures.CanvasHorizontalScrollable,
  GraphFeatures.CanvasVerticalScrollable,
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.A11yFeatures,
  GraphFeatures.LassoSelect,
  GraphFeatures.LimitBoundary,
]);

export const previewMode = new Set([GraphFeatures.NodeHoverView, GraphFeatures.PortHoverView, GraphFeatures.AutoFit]);
