export enum GraphFeatures {
  NodeDraggable = "nodeDraggable",
  NodeResizable = "nodeResizable",
  ClickNodeToSelect = "clickNodeToSelect",
  PanCanvas = "panCanvas",
  MultipleSelect = "multipleSelect",
  LassoSelect = "lassoSelect",
  Delete = "delete",
  AddNewNodes = "addNewNodes",
  AddNewEdges = "addNewEdges",
  AddNewPorts = "addNewPorts",
  AutoFit = "autoFit",
  CanvasHorizontalScrollable = "canvasHorizontalScrollable",
  CanvasVerticalScrollable = "canvasVerticalScrollable",
  NodeHoverView = "nodeHoverView",
  PortHoverView = "portHoverView",
  AddEdgesByKeyboard = "addEdgesByKeyboard",
  A11yFeatures = "a11YFeatures",
  EditNode = "editNode",
  AutoAlign = "autoAlign",
  UndoStack = "undoStack",
  CtrlKeyZoom = "ctrlKeyZoom",
  LimitBoundary = "limitBoundary",
  EditEdge = "editEdge",
}

export const allFeatures = new Set([
  GraphFeatures.NodeDraggable,
  GraphFeatures.NodeResizable,
  GraphFeatures.ClickNodeToSelect,
  GraphFeatures.PanCanvas,
  GraphFeatures.MultipleSelect,
  GraphFeatures.LassoSelect,
  GraphFeatures.Delete,
  GraphFeatures.AddNewNodes,
  GraphFeatures.AddNewEdges,
  GraphFeatures.AddNewPorts,
  GraphFeatures.CanvasHorizontalScrollable,
  GraphFeatures.CanvasVerticalScrollable,
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.AddEdgesByKeyboard,
  GraphFeatures.A11yFeatures,
  GraphFeatures.AutoFit,
  GraphFeatures.EditNode,
  GraphFeatures.AutoAlign,
  GraphFeatures.UndoStack,
  GraphFeatures.CtrlKeyZoom,
  GraphFeatures.LimitBoundary,
  GraphFeatures.EditEdge,
]);

export const defaultFeatures = new Set([
  GraphFeatures.NodeDraggable,
  GraphFeatures.NodeResizable,
  GraphFeatures.ClickNodeToSelect,
  GraphFeatures.PanCanvas,
  GraphFeatures.MultipleSelect,
  GraphFeatures.Delete,
  GraphFeatures.AddNewNodes,
  GraphFeatures.AddNewEdges,
  GraphFeatures.AddNewPorts,
  GraphFeatures.CanvasHorizontalScrollable,
  GraphFeatures.CanvasVerticalScrollable,
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.AddEdgesByKeyboard,
  GraphFeatures.A11yFeatures,
  GraphFeatures.EditNode,
  GraphFeatures.AutoAlign,
  GraphFeatures.UndoStack,
  GraphFeatures.CtrlKeyZoom,
  GraphFeatures.LimitBoundary,
]);

export const dataReadonlyMode = new Set([
  GraphFeatures.NodeDraggable,
  GraphFeatures.NodeResizable,
  GraphFeatures.ClickNodeToSelect,
  GraphFeatures.PanCanvas,
  GraphFeatures.MultipleSelect,
  GraphFeatures.CanvasHorizontalScrollable,
  GraphFeatures.CanvasVerticalScrollable,
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.A11yFeatures,
  GraphFeatures.CtrlKeyZoom,
  GraphFeatures.LimitBoundary,
]);

export const GanttChartFeatures = new Set([
  GraphFeatures.ClickNodeToSelect,
  GraphFeatures.CanvasHorizontalScrollable,
  GraphFeatures.CanvasVerticalScrollable,
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.A11yFeatures,
  GraphFeatures.LassoSelect,
  GraphFeatures.LimitBoundary,
]);

export const previewMode = new Set([
  GraphFeatures.NodeHoverView,
  GraphFeatures.PortHoverView,
  GraphFeatures.AutoFit,
]);
