name: Github pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Build site
        run: yarn build:site

      - name: Release pages
        if: github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925 # v2.5.0
        with:
          build_dir: ./dist/storybook/react-dag-editor
          commit_message: Update pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
