name: PR-gated

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version:
          - 18.x
          - 20.x
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node_version }}
      - name: yarn install
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
