name: PR-gated

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version:
          - 18.x
          - 20.x
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.node_version }}
      - name: yarn install
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
