name: npm-publish
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 18.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.node_version }}
      - name: yarn install
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@374314eadce0ca5353387666469a949f69414752 # 1.3.9
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "\\b[Rr]elease[:]? (\\S+)"
          workspace: "./dist/packages/react-dag-editor"
          publish_command: "yarn"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
